/**
 * Comprehensive porcelain / common git command examples (≥200).
 * Sourced from git documentation topics (extraction baseline for catalog builder).
 */
export const GIT_COMMANDS = [
  { command: 'git init', risk_class: 'low', topic: 'create' },
  { command: 'git init --bare', risk_class: 'low', topic: 'create' },
  { command: 'git clone <url>', risk_class: 'low', topic: 'create' },
  { command: 'git clone --depth 1 <url>', risk_class: 'low', topic: 'create' },
  { command: 'git clone --branch <branch> <url>', risk_class: 'low', topic: 'create' },
  { command: 'git status', risk_class: 'none', topic: 'status' },
  { command: 'git status -sb', risk_class: 'none', topic: 'status' },
  { command: 'git status --ignored', risk_class: 'none', topic: 'status' },
  { command: 'git diff', risk_class: 'none', topic: 'diff' },
  { command: 'git diff --staged', risk_class: 'none', topic: 'diff' },
  { command: 'git diff HEAD', risk_class: 'none', topic: 'diff' },
  { command: 'git diff <branch>...<other>', risk_class: 'none', topic: 'diff' },
  { command: 'git diff --stat', risk_class: 'none', topic: 'diff' },
  { command: 'git add <file>', risk_class: 'low', topic: 'stage' },
  { command: 'git add .', risk_class: 'low', topic: 'stage' },
  { command: 'git add -p', risk_class: 'low', topic: 'stage' },
  { command: 'git add -u', risk_class: 'low', topic: 'stage' },
  { command: 'git add -A', risk_class: 'low', topic: 'stage' },
  { command: 'git restore --staged <file>', risk_class: 'low', topic: 'stage' },
  { command: 'git restore <file>', risk_class: 'high', topic: 'undo' },
  { command: 'git restore --source=HEAD~1 <file>', risk_class: 'high', topic: 'undo' },
  { command: 'git commit -m "<message>"', risk_class: 'low', topic: 'commit' },
  { command: 'git commit -am "<message>"', risk_class: 'low', topic: 'commit' },
  { command: 'git commit --amend', risk_class: 'high', topic: 'commit' },
  { command: 'git commit --amend --no-edit', risk_class: 'high', topic: 'commit' },
  { command: 'git commit --fix', risk_class: 'low', topic: 'commit' },
  { command: 'git commit --allow-empty', risk_class: 'low', topic: 'commit' },
  { command: 'git log', risk_class: 'none', topic: 'history' },
  { command: 'git log --oneline', risk_class: 'none', topic: 'history' },
  { command: 'git log --graph --oneline --all', risk_class: 'none', topic: 'history' },
  { command: 'git log -p', risk_class: 'none', topic: 'history' },
  { command: 'git log --author="<name>"', risk_class: 'none', topic: 'history' },
  { command: 'git log --since="2 weeks ago"', risk_class: 'none', topic: 'history' },
  { command: 'git log -S"<text>"', risk_class: 'none', topic: 'history' },
  { command: 'git show', risk_class: 'none', topic: 'history' },
  { command: 'git show HEAD', risk_class: 'none', topic: 'history' },
  { command: 'git show <commit>', risk_class: 'none', topic: 'history' },
  { command: 'git blame <file>', risk_class: 'none', topic: 'history' },
  { command: 'git annotate <file>', risk_class: 'none', topic: 'history' },
  { command: 'git branch', risk_class: 'none', topic: 'branch' },
  { command: 'git branch -a', risk_class: 'none', topic: 'branch' },
  { command: 'git branch <name>', risk_class: 'low', topic: 'branch' },
  { command: 'git branch -d <name>', risk_class: 'low', topic: 'branch' },
  { command: 'git branch -D <name>', risk_class: 'high', topic: 'branch' },
  { command: 'git branch -m <old> <new>', risk_class: 'low', topic: 'branch' },
  { command: 'git branch -vv', risk_class: 'none', topic: 'branch' },
  { command: 'git switch <branch>', risk_class: 'low', topic: 'branch' },
  { command: 'git switch -c <name>', risk_class: 'low', topic: 'branch' },
  { command: 'git switch -', risk_class: 'low', topic: 'branch' },
  { command: 'git checkout <branch>', risk_class: 'low', topic: 'branch' },
  { command: 'git checkout -b <name>', risk_class: 'low', topic: 'branch' },
  { command: 'git checkout -- <file>', risk_class: 'high', topic: 'undo' },
  { command: 'git merge <branch>', risk_class: 'high', topic: 'merge' },
  { command: 'git merge --no-ff <branch>', risk_class: 'high', topic: 'merge' },
  { command: 'git merge --abort', risk_class: 'low', topic: 'merge' },
  { command: 'git merge --continue', risk_class: 'low', topic: 'merge' },
  { command: 'git rebase <branch>', risk_class: 'destructive', topic: 'rebase' },
  { command: 'git rebase -i HEAD~3', risk_class: 'destructive', topic: 'rebase' },
  { command: 'git rebase --abort', risk_class: 'low', topic: 'rebase' },
  { command: 'git rebase --continue', risk_class: 'high', topic: 'rebase' },
  { command: 'git rebase --skip', risk_class: 'high', topic: 'rebase' },
  { command: 'git pull', risk_class: 'high', topic: 'remote' },
  { command: 'git pull --rebase', risk_class: 'high', topic: 'remote' },
  { command: 'git pull origin <branch>', risk_class: 'high', topic: 'remote' },
  { command: 'git push', risk_class: 'high', topic: 'remote' },
  { command: 'git push -u origin HEAD', risk_class: 'high', topic: 'remote' },
  { command: 'git push --force-with-lease', risk_class: 'destructive', topic: 'remote' },
  { command: 'git push --force', risk_class: 'destructive', topic: 'remote' },
  { command: 'git push origin --delete <branch>', risk_class: 'high', topic: 'remote' },
  { command: 'git push --tags', risk_class: 'high', topic: 'remote' },
  { command: 'git fetch', risk_class: 'low', topic: 'remote' },
  { command: 'git fetch --all --prune', risk_class: 'low', topic: 'remote' },
  { command: 'git fetch origin', risk_class: 'low', topic: 'remote' },
  { command: 'git remote -v', risk_class: 'none', topic: 'remote' },
  { command: 'git remote add origin <url>', risk_class: 'low', topic: 'remote' },
  { command: 'git remote set-url origin <url>', risk_class: 'low', topic: 'remote' },
  { command: 'git remote remove origin', risk_class: 'low', topic: 'remote' },
  { command: 'git remote rename origin upstream', risk_class: 'low', topic: 'remote' },
  { command: 'git ls-remote origin', risk_class: 'none', topic: 'remote' },
  { command: 'git reset', risk_class: 'high', topic: 'undo' },
  { command: 'git reset HEAD <file>', risk_class: 'low', topic: 'undo' },
  { command: 'git reset --soft HEAD~1', risk_class: 'high', topic: 'undo' },
  { command: 'git reset --mixed HEAD~1', risk_class: 'high', topic: 'undo' },
  { command: 'git reset --hard HEAD~1', risk_class: 'destructive', topic: 'undo' },
  { command: 'git reset --hard origin/main', risk_class: 'destructive', topic: 'undo' },
  { command: 'git revert HEAD', risk_class: 'high', topic: 'undo' },
  { command: 'git revert <commit>', risk_class: 'high', topic: 'undo' },
  { command: 'git revert --no-commit <commit>', risk_class: 'high', topic: 'undo' },
  { command: 'git clean -n', risk_class: 'none', topic: 'clean' },
  { command: 'git clean -fd', risk_class: 'destructive', topic: 'clean' },
  { command: 'git clean -fdx', risk_class: 'destructive', topic: 'clean' },
  { command: 'git stash', risk_class: 'low', topic: 'stash' },
  { command: 'git stash push -m "<message>"', risk_class: 'low', topic: 'stash' },
  { command: 'git stash push -u', risk_class: 'low', topic: 'stash' },
  { command: 'git stash list', risk_class: 'none', topic: 'stash' },
  { command: 'git stash show', risk_class: 'none', topic: 'stash' },
  { command: 'git stash pop', risk_class: 'high', topic: 'stash' },
  { command: 'git stash apply', risk_class: 'low', topic: 'stash' },
  { command: 'git stash drop', risk_class: 'high', topic: 'stash' },
  { command: 'git stash clear', risk_class: 'destructive', topic: 'stash' },
  { command: 'git tag', risk_class: 'none', topic: 'tag' },
  { command: 'git tag <name>', risk_class: 'low', topic: 'tag' },
  { command: 'git tag -a <name> -m "<message>"', risk_class: 'low', topic: 'tag' },
  { command: 'git tag -d <name>', risk_class: 'high', topic: 'tag' },
  { command: 'git push origin <tag>', risk_class: 'high', topic: 'tag' },
  { command: 'git push origin :refs/tags/<tag>', risk_class: 'high', topic: 'tag' },
  { command: 'git describe --tags', risk_class: 'none', topic: 'tag' },
  { command: 'git config --list', risk_class: 'none', topic: 'config' },
  { command: 'git config user.name "<name>"', risk_class: 'low', topic: 'config' },
  { command: 'git config user.email "<email>"', risk_class: 'low', topic: 'config' },
  { command: 'git config --global user.name "<name>"', risk_class: 'low', topic: 'config' },
  { command: 'git config --global user.email "<email>"', risk_class: 'low', topic: 'config' },
  { command: 'git config core.editor "<editor>"', risk_class: 'low', topic: 'config' },
  { command: 'git config --global init.defaultBranch main', risk_class: 'low', topic: 'config' },
  { command: 'git config --unset <key>', risk_class: 'low', topic: 'config' },
  { command: 'git help <command>', risk_class: 'none', topic: 'help' },
  { command: 'git help -a', risk_class: 'none', topic: 'help' },
  { command: 'git version', risk_class: 'none', topic: 'help' },
  { command: 'git cherry-pick <commit>', risk_class: 'high', topic: 'history' },
  { command: 'git cherry-pick --abort', risk_class: 'low', topic: 'history' },
  { command: 'git cherry-pick --continue', risk_class: 'high', topic: 'history' },
  { command: 'git bisect start', risk_class: 'low', topic: 'debug' },
  { command: 'git bisect bad', risk_class: 'low', topic: 'debug' },
  { command: 'git bisect good', risk_class: 'low', topic: 'debug' },
  { command: 'git bisect reset', risk_class: 'low', topic: 'debug' },
  { command: 'git reflog', risk_class: 'none', topic: 'undo' },
  { command: 'git reflog expire --expire=now --all', risk_class: 'destructive', topic: 'undo' },
  { command: 'git fsck', risk_class: 'none', topic: 'debug' },
  { command: 'git gc', risk_class: 'low', topic: 'maintenance' },
  { command: 'git gc --prune=now', risk_class: 'high', topic: 'maintenance' },
  { command: 'git prune', risk_class: 'high', topic: 'maintenance' },
  { command: 'git repack -ad', risk_class: 'low', topic: 'maintenance' },
  { command: 'git maintenance run', risk_class: 'low', topic: 'maintenance' },
  { command: 'git submodule add <url>', risk_class: 'low', topic: 'submodule' },
  { command: 'git submodule update --init --recursive', risk_class: 'low', topic: 'submodule' },
  { command: 'git submodule sync', risk_class: 'low', topic: 'submodule' },
  { command: 'git submodule deinit -f <path>', risk_class: 'high', topic: 'submodule' },
  { command: 'git worktree add <path> <branch>', risk_class: 'low', topic: 'worktree' },
  { command: 'git worktree list', risk_class: 'none', topic: 'worktree' },
  { command: 'git worktree remove <path>', risk_class: 'high', topic: 'worktree' },
  { command: 'git worktree prune', risk_class: 'low', topic: 'worktree' },
  { command: 'git sparse-checkout init --cone', risk_class: 'high', topic: 'sparse' },
  { command: 'git sparse-checkout set <dir>', risk_class: 'high', topic: 'sparse' },
  { command: 'git sparse-checkout disable', risk_class: 'high', topic: 'sparse' },
  { command: 'git mv <old> <new>', risk_class: 'low', topic: 'files' },
  { command: 'git rm <file>', risk_class: 'high', topic: 'files' },
  { command: 'git rm --cached <file>', risk_class: 'low', topic: 'files' },
  { command: 'git grep "<pattern>"', risk_class: 'none', topic: 'search' },
  { command: 'git grep -n "<pattern>"', risk_class: 'none', topic: 'search' },
  { command: 'git shortlog -sn', risk_class: 'none', topic: 'history' },
  { command: 'git archive --format=zip HEAD -o repo.zip', risk_class: 'none', topic: 'archive' },
  { command: 'git bundle create repo.bundle --all', risk_class: 'low', topic: 'bundle' },
  { command: 'git bundle verify repo.bundle', risk_class: 'none', topic: 'bundle' },
  { command: 'git notes add -m "<message>"', risk_class: 'low', topic: 'notes' },
  { command: 'git notes show', risk_class: 'none', topic: 'notes' },
  { command: 'git replace <object> <replacement>', risk_class: 'destructive', topic: 'advanced' },
  { command: 'git filter-branch --tree-filter \'rm -f password.txt\' HEAD', risk_class: 'destructive', topic: 'history' },
  { command: 'git rebase --onto <newbase> <upstream> <branch>', risk_class: 'destructive', topic: 'rebase' },
  { command: 'git range-diff <old>...<new>', risk_class: 'none', topic: 'diff' },
  { command: 'git format-patch -1 HEAD', risk_class: 'none', topic: 'patch' },
  { command: 'git format-patch -3 HEAD', risk_class: 'none', topic: 'patch' },
  { command: 'git am <patch>', risk_class: 'high', topic: 'patch' },
  { command: 'git apply <patch>', risk_class: 'high', topic: 'patch' },
  { command: 'git apply --check <patch>', risk_class: 'none', topic: 'patch' },
  { command: 'git mergetool', risk_class: 'low', topic: 'merge' },
  { command: 'git difftool', risk_class: 'none', topic: 'diff' },
  { command: 'git cherry -v', risk_class: 'none', topic: 'branch' },
  { command: 'git show-branch', risk_class: 'none', topic: 'branch' },
  { command: 'git name-rev HEAD', risk_class: 'none', topic: 'advanced' },
  { command: 'git rev-parse HEAD', risk_class: 'none', topic: 'advanced' },
  { command: 'git rev-parse --abbrev-ref HEAD', risk_class: 'none', topic: 'advanced' },
  { command: 'git rev-list --count HEAD', risk_class: 'none', topic: 'advanced' },
  { command: 'git merge-base main feature', risk_class: 'none', topic: 'merge' },
  { command: 'git for-each-ref --format="%(refname)"', risk_class: 'none', topic: 'advanced' },
  { command: 'git update-ref -d refs/heads/<branch>', risk_class: 'destructive', topic: 'advanced' },
  { command: 'git symbolic-ref HEAD refs/heads/main', risk_class: 'high', topic: 'advanced' },
  { command: 'git check-ignore -v <file>', risk_class: 'none', topic: 'debug' },
  { command: 'git check-attr -a -- <file>', risk_class: 'none', topic: 'debug' },
  { command: 'git ls-files', risk_class: 'none', topic: 'files' },
  { command: 'git ls-files -o --exclude-standard', risk_class: 'none', topic: 'files' },
  { command: 'git update-index --assume-unchanged <file>', risk_class: 'high', topic: 'advanced' },
  { command: 'git update-index --no-assume-unchanged <file>', risk_class: 'low', topic: 'advanced' },
  { command: 'git count-objects -vH', risk_class: 'none', topic: 'maintenance' },
  { command: 'git verify-commit HEAD', risk_class: 'none', topic: 'security' },
  { command: 'git verify-tag <tag>', risk_class: 'none', topic: 'security' },
  { command: 'git interpret-trailers --trailer "Signed-off-by: You" COMMIT_EDITMSG', risk_class: 'low', topic: 'commit' },
  { command: 'git pull --ff-only', risk_class: 'high', topic: 'remote' },
  { command: 'git push --all', risk_class: 'high', topic: 'remote' },
  { command: 'git fetch origin main:main', risk_class: 'high', topic: 'remote' },
  { command: 'git checkout --orphan <name>', risk_class: 'high', topic: 'branch' },
  { command: 'git commit --fix -m "<message>"', risk_class: 'high', topic: 'commit' },
  { command: 'git stash branch <name>', risk_class: 'low', topic: 'stash' },
  { command: 'git log --follow -- <file>', risk_class: 'none', topic: 'history' },
  { command: 'git blame -L 10,20 <file>', risk_class: 'none', topic: 'history' },
  { command: 'git diff --name-only', risk_class: 'none', topic: 'diff' },
  { command: 'git diff --name-status', risk_class: 'none', topic: 'diff' },
  { command: 'git show --stat', risk_class: 'none', topic: 'history' },
  { command: 'git branch --contains <commit>', risk_class: 'none', topic: 'branch' },
  { command: 'git branch --merged', risk_class: 'none', topic: 'branch' },
  { command: 'git branch --no-merged', risk_class: 'none', topic: 'branch' },
  { command: 'git tag -l "<pattern>"', risk_class: 'none', topic: 'tag' },
  { command: 'git config --global alias.st status', risk_class: 'low', topic: 'config' },
  { command: 'git config --global core.autocrlf true', risk_class: 'low', topic: 'config' },
  { command: 'git config --global pull.rebase true', risk_class: 'low', topic: 'config' },
  { command: 'git rebase --autosquash', risk_class: 'destructive', topic: 'rebase' },
  { command: 'git commit --fix --amend', risk_class: 'high', topic: 'commit' },
  { command: 'git restore --worktree --staged <file>', risk_class: 'high', topic: 'undo' },
  { command: 'git switch --detach HEAD~1', risk_class: 'high', topic: 'branch' },
  { command: 'git clone --recurse-submodules <url>', risk_class: 'low', topic: 'submodule' },
  { command: 'git push origin HEAD:refs/heads/<branch>', risk_class: 'high', topic: 'remote' },
  { command: 'git fetch --tags', risk_class: 'low', topic: 'remote' },
  { command: 'git describe --always', risk_class: 'none', topic: 'tag' },
  { command: 'git log --merges', risk_class: 'none', topic: 'history' },
  { command: 'git log --no-merges', risk_class: 'none', topic: 'history' },
  { command: 'git shortlog', risk_class: 'none', topic: 'history' },
  { command: 'git whatchanged', risk_class: 'none', topic: 'history' },
  { command: 'git request-pull <start> <url>', risk_class: 'none', topic: 'remote' },
  { command: 'git instaweb', risk_class: 'low', topic: 'help' },
  { command: 'git bugreport', risk_class: 'none', topic: 'help' },
  { command: 'git citool', risk_class: 'none', topic: 'gui' },
  { command: 'git gui', risk_class: 'none', topic: 'gui' },
  { command: 'git stage <file>', risk_class: 'low', topic: 'stage' },
];

// Ensure uniqueness by command string
const seen = new Set();
export const UNIQUE_GIT_COMMANDS = GIT_COMMANDS.filter((c) => {
  if (seen.has(c.command)) return false;
  seen.add(c.command);
  return true;
});
