#!/usr/bin/env bun
/**
 * Export seeded git-commands.db → apps/web/public/catalog/web-catalog.db (+ .sha256).
 * Model weights are separate (not in this blob).
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync, statSync, copyFileSync } from 'node:fs';
import path from 'node:path';
import { exportWebCatalog, defaultWebCatalogPath } from '../../../common/src/search/webCatalog.js';
import { defaultDbPath, defaultThresholdsPath, PACKAGE_ROOT } from '../../../common/src/lib/paths.js';
import { sha256Buffer } from '../../../common/src/lib/checksum.js';

const dbPath = process.env.GIT_GRASP_DB || defaultDbPath();
const thresholdsPath = process.env.GIT_GRASP_THRESHOLDS || defaultThresholdsPath();
const outPath = defaultWebCatalogPath();
const constantsOut = path.join(PACKAGE_ROOT, 'apps', 'web', 'src', 'lib', 'assetSizes.ts');
const sqlJsVendorDir = path.join(PACKAGE_ROOT, 'apps', 'web', 'public', 'vendor', 'sql.js');
const sqlJsDist = path.join(PACKAGE_ROOT, 'node_modules', 'sql.js', 'dist');
const transformersVendorDir = path.join(PACKAGE_ROOT, 'apps', 'web', 'public', 'vendor', 'transformers');
const transformersDist = path.join(PACKAGE_ROOT, 'node_modules', '@huggingface', 'transformers', 'dist');

if (!existsSync(dbPath)) {
  console.error(`Database missing: ${dbPath}. Run bun run ship first.`);
  process.exit(1);
}

const result = exportWebCatalog(dbPath, outPath, { thresholdsPath });
const bytes = readFileSync(outPath);
const hash = result.hash || sha256Buffer(bytes);
const size = result.size || statSync(outPath).size;

const MODEL_BYTES_ESTIMATE = 90 * 1024 * 1024;
const catalogMb = Math.ceil(size / (1024 * 1024));
const modelMb = Math.ceil(MODEL_BYTES_ESTIMATE / (1024 * 1024));
// Overlay cites catalog + model separately (B1-A); total label is sum for UX.
const totalMb = catalogMb + modelMb;

mkdirSync(path.dirname(constantsOut), { recursive: true });
writeFileSync(
  constantsOut,
  `/** Auto-generated by apps/web/scripts/export-web-pack.ts — do not edit by hand. */
export const WEB_PACK_BYTES = ${size};
export const WEB_PACK_SHA256 = '${hash}';
export const WEB_CATALOG_URL = '/catalog/web-catalog.db';
export const MODEL_BYTES_ESTIMATE = ${MODEL_BYTES_ESTIMATE};
export const MODEL_DOWNLOAD_MB = ${modelMb};
export const MODEL_DOWNLOAD_LABEL = '~${modelMb} MB';
export const PLAYGROUND_DOWNLOAD_MB = ${totalMb};
export const PLAYGROUND_DOWNLOAD_LABEL = '~${totalMb} MB (catalog ~${catalogMb} MB + model ~${modelMb} MB)';
`,
);

console.log(`Wrote ${outPath}`);
console.log(`Catalog: ${(size / (1024 * 1024)).toFixed(2)} MB`);
console.log(`SHA256: ${hash}`);
console.log(`search_algorithm_version: ${result.searchAlgorithmVersion}`);
console.log(`Constants → ${constantsOut}`);

mkdirSync(sqlJsVendorDir, { recursive: true });
for (const name of ['sql-wasm.wasm', 'sql-wasm-browser.wasm']) {
  const src = path.join(sqlJsDist, name);
  if (!existsSync(src)) continue;
  const dest = path.join(sqlJsVendorDir, name);
  copyFileSync(src, dest);
  console.log(`Vendor WASM → ${dest}`);
}

mkdirSync(transformersVendorDir, { recursive: true });
for (const name of ['ort-wasm-simd-threaded.jsep.mjs', 'ort-wasm-simd-threaded.jsep.wasm']) {
  const src = path.join(transformersDist, name);
  if (!existsSync(src)) {
    console.error(`Transformers ONNX runtime missing: ${src}`);
    process.exit(1);
  }
  const dest = path.join(transformersVendorDir, name);
  copyFileSync(src, dest);
  console.log(`Vendor ONNX → ${dest}`);
}
