import { readFileSync, writeFileSync } from 'node:fs';
import { migrateGoldenCase } from '@git-help/core/eval/judge.js';
import { DEFAULT_GLOSSARY } from '@git-help/core/catalog/step0Glossary.js';

const existing = JSON.parse(readFileSync('eval/golden/cases.json', 'utf8'));
const migrated = existing.map((c) => migrateGoldenCase(c, DEFAULT_GLOSSARY));

const extras = [
  {
    id: 'branch-current-01',
    query: 'what branch am I on',
    expectedCommand: 'git branch',
    expectedExample: 'git branch --show-current',
    acceptableCommands: ['git branch'],
    acceptableExamples: [
      'git branch --show-current',
      'git rev-parse --abbrev-ref HEAD',
      'git symbolic-ref --short HEAD',
    ],
    expectedSimplestExample: 'git branch --show-current',
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    judgeNotes: 'Prefer porcelain simplest',
    tags: ['branch', 'simplest'],
  },
  {
    id: 'branch-current-02',
    query: 'print the name of my current branch',
    expectedCommand: 'git branch',
    expectedExample: 'git branch --show-current',
    acceptableExamples: ['git branch --show-current'],
    expectedSimplestExample: 'git branch --show-current',
    preferSimplest: true,
    expectedSkillBand: [1, 2],
    tags: ['branch', 'simplest'],
  },
  {
    id: 'status-02',
    query: 'am I clean or do I have uncommitted changes',
    expectedCommand: 'git status',
    expectedExample: 'git status',
    acceptableExamples: ['git status', 'git status -sb'],
    preferSimplest: true,
    expectedSkillBand: [1, 2],
    tags: ['status'],
  },
  {
    id: 'status-03',
    query: 'short status branch and dirty files',
    expectedCommand: 'git status',
    expectedExample: 'git status -sb',
    acceptableExamples: ['git status -sb', 'git status'],
    preferSimplest: false,
    expectedSkillBand: [2, 4],
    tags: ['status'],
  },
  {
    id: 'diff-02',
    query: 'what will be in my next commit',
    expectedCommand: 'git diff',
    expectedExample: 'git diff --staged',
    acceptableExamples: ['git diff --staged'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['diff'],
  },
  {
    id: 'diff-03',
    query: 'show unstaged changes only',
    expectedCommand: 'git diff',
    expectedExample: 'git diff',
    acceptableExamples: ['git diff'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['diff'],
  },
  {
    id: 'add-01',
    query: 'stage one file for commit',
    expectedCommand: 'git add',
    expectedExample: 'git add app.js',
    acceptableExamples: ['git add app.js', 'git add .'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['stage'],
  },
  {
    id: 'add-02',
    query: 'interactively pick hunks to stage',
    expectedCommand: 'git add',
    expectedExample: 'git add -p',
    acceptableExamples: ['git add -p'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['stage'],
  },
  {
    id: 'commit-02',
    query: 'amend last commit keep same message',
    expectedCommand: 'git commit',
    expectedExample: 'git commit --amend --no-edit',
    acceptableExamples: ['git commit --amend --no-edit', 'git commit --amend'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['commit'],
  },
  {
    id: 'commit-03',
    query: 'stage all tracked changes and commit',
    expectedCommand: 'git commit',
    expectedExample: 'git commit -am "Fix typo"',
    acceptableExamples: ['git commit -am "Fix typo"'],
    preferSimplest: true,
    expectedSkillBand: [2, 3],
    tags: ['commit'],
  },
  {
    id: 'log-02',
    query: 'pretty graph of all branches',
    expectedCommand: 'git log',
    expectedExample: 'git log --graph --oneline --all',
    acceptableExamples: ['git log --graph --oneline --all'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['history'],
  },
  {
    id: 'log-03',
    query: 'who last touched this line',
    expectedCommand: 'git blame',
    expectedExample: 'git blame app.js',
    acceptableExamples: ['git blame app.js', 'git annotate app.js'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['history'],
  },
  {
    id: 'switch-01',
    query: 'go back to previous branch',
    expectedCommand: 'git switch',
    expectedExample: 'git switch -',
    acceptableExamples: ['git switch -', 'git checkout -'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['branch'],
  },
  {
    id: 'switch-02',
    query: 'check out main branch',
    expectedCommand: 'git switch',
    expectedExample: 'git switch main',
    acceptableExamples: ['git switch main', 'git checkout main'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['branch'],
  },
  {
    id: 'fetch-01',
    query: 'update remote tracking branches and prune deleted ones',
    expectedCommand: 'git fetch',
    expectedExample: 'git fetch --all --prune',
    acceptableExamples: ['git fetch --all --prune', 'git fetch'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['remote'],
  },
  {
    id: 'pull-02',
    query: 'pull with rebase instead of merge',
    expectedCommand: 'git pull',
    expectedExample: 'git pull --rebase',
    acceptableExamples: ['git pull --rebase'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['remote'],
  },
  {
    id: 'push-02',
    query: 'force push safely without clobbering others',
    expectedCommand: 'git push',
    expectedExample: 'git push --force-with-lease',
    acceptableExamples: ['git push --force-with-lease'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['remote'],
  },
  {
    id: 'remote-01',
    query: 'list remotes with urls',
    expectedCommand: 'git remote',
    expectedExample: 'git remote -v',
    acceptableExamples: ['git remote -v'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['remote'],
  },
  {
    id: 'stash-02',
    query: 'bring back my stash and drop it',
    expectedCommand: 'git stash',
    expectedExample: 'git stash pop',
    acceptableExamples: ['git stash pop'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['stash'],
  },
  {
    id: 'stash-03',
    query: 'stash including untracked files',
    expectedCommand: 'git stash',
    expectedExample: 'git stash -u',
    acceptableExamples: ['git stash -u', 'git stash --include-untracked'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['stash'],
  },
  {
    id: 'undo-soft-02',
    query: 'uncommit but keep my work staged soft',
    expectedCommand: 'git reset',
    expectedExample: 'git reset --soft HEAD~1',
    acceptableExamples: ['git reset --soft HEAD~1'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['undo'],
  },
  {
    id: 'undo-restore-01',
    query: 'unstage a file keep changes in working tree',
    expectedCommand: 'git restore',
    expectedExample: 'git restore --staged app.js',
    acceptableExamples: ['git restore --staged app.js', 'git reset HEAD app.js'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['undo'],
  },
  {
    id: 'undo-revert-01',
    query: 'make a new commit that undoes the last one',
    expectedCommand: 'git revert',
    expectedExample: 'git revert HEAD',
    acceptableExamples: ['git revert HEAD', 'git revert abc1234'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['undo'],
  },
  {
    id: 'rebase-abort-01',
    query: 'cancel an in-progress rebase',
    expectedCommand: 'git rebase',
    expectedExample: 'git rebase --abort',
    acceptableExamples: ['git rebase --abort'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['rebase'],
  },
  {
    id: 'merge-abort-01',
    query: 'cancel an in-progress merge',
    expectedCommand: 'git merge',
    expectedExample: 'git merge --abort',
    acceptableExamples: ['git merge --abort'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['merge'],
  },
  {
    id: 'clean-01',
    query: 'preview which untracked files would be deleted',
    expectedCommand: 'git clean',
    expectedExample: 'git clean -n',
    acceptableExamples: ['git clean -n', 'git clean --dry-run'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['clean'],
  },
  {
    id: 'clone-01',
    query: 'clone a repo shallow',
    expectedCommand: 'git clone',
    expectedExample: 'git clone --depth 1 https://github.com/example/repo.git',
    acceptableExamples: [
      'git clone --depth 1 https://github.com/example/repo.git',
      'git clone https://github.com/example/repo.git',
    ],
    preferSimplest: false,
    expectedSkillBand: [2, 4],
    tags: ['create'],
  },
  {
    id: 'init-01',
    query: 'start a new git repository here',
    expectedCommand: 'git init',
    expectedExample: 'git init',
    acceptableExamples: ['git init'],
    preferSimplest: true,
    expectedSkillBand: [1, 2],
    tags: ['create'],
  },
  {
    id: 'show-01',
    query: 'show the latest commit contents',
    expectedCommand: 'git show',
    expectedExample: 'git show',
    acceptableExamples: ['git show', 'git show HEAD'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['history'],
  },
  {
    id: 'tag-01',
    query: 'create an annotated release tag',
    expectedCommand: 'git tag',
    expectedExample: 'git tag -a v1.0.0 -m "Fix typo"',
    acceptableExamples: ['git tag -a v1.0.0 -m "Fix typo"', 'git tag v1.0.0'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['tag'],
  },
  {
    id: 'grep-01',
    query: 'search the repo for TODO comments',
    expectedCommand: 'git grep',
    expectedExample: 'git grep "TODO"',
    acceptableExamples: ['git grep "TODO"', 'git grep -n "TODO"'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['search'],
  },
  {
    id: 'config-01',
    query: 'set my global email address',
    expectedCommand: 'git config',
    expectedExample: 'git config --global user.email "dev@example.com"',
    acceptableExamples: ['git config --global user.email "dev@example.com"'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['config'],
  },
  {
    id: 'reflog-01',
    query: 'show where HEAD has pointed recently',
    expectedCommand: 'git reflog',
    expectedExample: 'git reflog',
    acceptableExamples: ['git reflog'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['history'],
  },
  {
    id: 'cherry-01',
    query: 'apply a single commit onto this branch',
    expectedCommand: 'git cherry-pick',
    expectedExample: 'git cherry-pick abc1234',
    acceptableExamples: ['git cherry-pick abc1234'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['history'],
  },
  {
    id: 'bisect-01',
    query: 'start finding which commit introduced a bug',
    expectedCommand: 'git bisect',
    expectedExample: 'git bisect start',
    acceptableExamples: ['git bisect start'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['debug'],
  },
  {
    id: 'worktree-01',
    query: 'add a linked worktree for a feature branch',
    expectedCommand: 'git worktree',
    expectedExample: 'git worktree add ../hotfix feature/login',
    acceptableExamples: ['git worktree add ../hotfix feature/login'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['worktree'],
  },
  {
    id: 'submodule-01',
    query: 'initialize and update all submodules recursively',
    expectedCommand: 'git submodule',
    expectedExample: 'git submodule update --init --recursive',
    acceptableExamples: ['git submodule update --init --recursive'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['submodule'],
  },
  {
    id: 'rm-cached-01',
    query: 'stop tracking a file but keep it on disk',
    expectedCommand: 'git rm',
    expectedExample: 'git rm --cached app.js',
    acceptableExamples: ['git rm --cached app.js'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['stage'],
  },
  {
    id: 'merge-01',
    query: 'merge main into my branch',
    expectedCommand: 'git merge',
    expectedExample: 'git merge main',
    acceptableExamples: ['git merge main'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['merge'],
  },
  {
    id: 'rebase-01',
    query: 'rebase my branch onto main',
    expectedCommand: 'git rebase',
    expectedExample: 'git rebase main',
    acceptableExamples: ['git rebase main'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['rebase'],
  },
  {
    id: 'nt-01',
    query: 'i messed up my last save how do i unsaved but keep files',
    expectedCommand: 'git reset',
    expectedExample: 'git reset --soft HEAD~1',
    acceptableExamples: ['git reset --soft HEAD~1'],
    preferSimplest: true,
    expectedSkillBand: ['non-technical', 'beginner'],
    tags: ['undo', 'non-technical'],
  },
  {
    id: 'nt-02',
    query: 'which line of work am i on right now',
    expectedCommand: 'git branch',
    expectedExample: 'git branch --show-current',
    acceptableExamples: ['git branch --show-current'],
    preferSimplest: true,
    expectedSkillBand: ['non-technical', 'beginner'],
    tags: ['branch', 'non-technical'],
  },
  {
    id: 'nt-03',
    query: 'hide my unfinished work for a minute',
    expectedCommand: 'git stash',
    expectedExample: 'git stash',
    acceptableExamples: ['git stash'],
    preferSimplest: true,
    expectedSkillBand: ['non-technical', 2],
    tags: ['stash', 'non-technical'],
  },
  {
    id: 'expert-01',
    query: 'read the symbolic ref for HEAD short name',
    expectedCommand: 'git symbolic-ref',
    expectedExample: 'git symbolic-ref --short HEAD',
    acceptableExamples: ['git symbolic-ref --short HEAD', 'git symbolic-ref HEAD'],
    preferSimplest: false,
    expectedSkillBand: [4, 4],
    tags: ['branch', 'expert'],
  },
  {
    id: 'expert-02',
    query: 'abbrev-ref HEAD via rev-parse',
    expectedCommand: 'git rev-parse',
    expectedExample: 'git rev-parse --abbrev-ref HEAD',
    acceptableExamples: ['git rev-parse --abbrev-ref HEAD'],
    preferSimplest: false,
    expectedSkillBand: [4, 4],
    tags: ['branch', 'expert'],
  },
  {
    id: 'simplest-vs-plumbing-01',
    query: 'current branch name please',
    expectedCommand: 'git branch',
    expectedExample: 'git branch --show-current',
    acceptableExamples: [
      'git branch --show-current',
      'git rev-parse --abbrev-ref HEAD',
      'git symbolic-ref --short HEAD',
    ],
    expectedSimplestExample: 'git branch --show-current',
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['simplest'],
  },
  {
    id: 'push-03',
    query: 'just push my commits',
    expectedCommand: 'git push',
    expectedExample: 'git push',
    acceptableExamples: ['git push', 'git push -u origin HEAD'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['remote'],
  },
  {
    id: 'pull-03',
    query: 'get latest from the remote',
    expectedCommand: 'git pull',
    expectedExample: 'git pull',
    acceptableExamples: ['git pull', 'git fetch'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['remote'],
  },
  {
    id: 'diff-04',
    query: 'compare working tree to last commit',
    expectedCommand: 'git diff',
    expectedExample: 'git diff HEAD',
    acceptableExamples: ['git diff HEAD', 'git diff'],
    preferSimplest: false,
    expectedSkillBand: [2, 4],
    tags: ['diff'],
  },
  {
    id: 'add-03',
    query: 'stage everything in this folder',
    expectedCommand: 'git add',
    expectedExample: 'git add .',
    acceptableExamples: ['git add .', 'git add -A'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['stage'],
  },
  {
    id: 'commit-04',
    query: 'write a commit message for staged files',
    expectedCommand: 'git commit',
    expectedExample: 'git commit -m "Fix typo"',
    acceptableExamples: ['git commit -m "Fix typo"'],
    preferSimplest: true,
    expectedSkillBand: [1, 2],
    tags: ['commit'],
  },
  {
    id: 'branch-list-01',
    query: 'list my local branches',
    expectedCommand: 'git branch',
    expectedExample: 'git branch',
    acceptableExamples: ['git branch', 'git branch -a'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['branch'],
  },
  {
    id: 'branch-delete-01',
    query: 'delete a merged feature branch',
    expectedCommand: 'git branch',
    expectedExample: 'git branch -d feature/login',
    acceptableExamples: ['git branch -d feature/login'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['branch'],
  },
  {
    id: 'help-01',
    query: 'open help for the commit command',
    expectedCommand: 'git help',
    expectedExample: 'git help commit',
    acceptableExamples: ['git help commit', 'git commit --help'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['help'],
  },
  {
    id: 'version-01',
    query: 'what git version am i running',
    expectedCommand: 'git --version',
    expectedExample: 'git --version',
    acceptableExamples: ['git --version', 'git version'],
    preferSimplest: true,
    expectedSkillBand: [1, 2],
    tags: ['help'],
  },
  {
    id: 'fetch-02',
    query: 'fetch from origin only',
    expectedCommand: 'git fetch',
    expectedExample: 'git fetch origin',
    acceptableExamples: ['git fetch origin', 'git fetch'],
    preferSimplest: true,
    expectedSkillBand: [2, 3],
    tags: ['remote'],
  },
  {
    id: 'merge-ff-01',
    query: 'merge feature without fast-forward',
    expectedCommand: 'git merge',
    expectedExample: 'git merge --no-ff feature/login',
    acceptableExamples: ['git merge --no-ff feature/login'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['merge'],
  },
  {
    id: 'rebase-i-01',
    query: 'interactively rewrite last three commits',
    expectedCommand: 'git rebase',
    expectedExample: 'git rebase -i HEAD~3',
    acceptableExamples: ['git rebase -i HEAD~3'],
    preferSimplest: true,
    expectedSkillBand: [4, 4],
    tags: ['rebase'],
  },
  {
    id: 'stash-list-01',
    query: 'list my stashes',
    expectedCommand: 'git stash',
    expectedExample: 'git stash list',
    acceptableExamples: ['git stash list'],
    preferSimplest: true,
    expectedSkillBand: [2, 3],
    tags: ['stash'],
  },
  {
    id: 'show-02',
    query: 'inspect commit abc1234',
    expectedCommand: 'git show',
    expectedExample: 'git show abc1234',
    acceptableExamples: ['git show abc1234'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['history'],
  },
  {
    id: 'restore-02',
    query: 'discard local edits to a file',
    expectedCommand: 'git restore',
    expectedExample: 'git restore app.js',
    acceptableExamples: ['git restore app.js', 'git checkout -- app.js'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['undo'],
  },
  {
    id: 'clone-02',
    query: 'clone the example github repo',
    expectedCommand: 'git clone',
    expectedExample: 'git clone https://github.com/example/repo.git',
    acceptableExamples: ['git clone https://github.com/example/repo.git'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['create'],
  },
  {
    id: 'config-02',
    query: 'set my git username',
    expectedCommand: 'git config',
    expectedExample: 'git config user.name "alice"',
    acceptableExamples: [
      'git config user.name "alice"',
      'git config --global user.name "alice"',
    ],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['config'],
  },
  {
    id: 'tag-list-01',
    query: 'list all tags',
    expectedCommand: 'git tag',
    expectedExample: 'git tag -l',
    acceptableExamples: ['git tag -l', 'git tag'],
    preferSimplest: true,
    expectedSkillBand: [1, 3],
    tags: ['tag'],
  },
  {
    id: 'worktree-list-01',
    query: 'list linked worktrees',
    expectedCommand: 'git worktree',
    expectedExample: 'git worktree list',
    acceptableExamples: ['git worktree list'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['worktree'],
  },
  {
    id: 'submodule-status-01',
    query: 'show submodule status',
    expectedCommand: 'git submodule',
    expectedExample: 'git submodule status',
    acceptableExamples: ['git submodule status'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['submodule'],
  },
  {
    id: 'notes-01',
    query: 'add a note to HEAD',
    expectedCommand: 'git notes',
    expectedExample: 'git notes add -m "Fix typo"',
    acceptableExamples: ['git notes add -m "Fix typo"'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['notes'],
  },
  {
    id: 'shortlog-01',
    query: 'summary of commits by author',
    expectedCommand: 'git shortlog',
    expectedExample: 'git shortlog -sn',
    acceptableExamples: ['git shortlog -sn', 'git shortlog'],
    preferSimplest: true,
    expectedSkillBand: [2, 4],
    tags: ['history'],
  },
  {
    id: 'describe-01',
    query: 'describe current commit with nearest tag',
    expectedCommand: 'git describe',
    expectedExample: 'git describe --tags',
    acceptableExamples: ['git describe --tags', 'git describe'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['history'],
  },
  {
    id: 'ls-files-01',
    query: 'list tracked files in the index',
    expectedCommand: 'git ls-files',
    expectedExample: 'git ls-files',
    acceptableExamples: ['git ls-files'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['files'],
  },
  {
    id: 'check-ignore-01',
    query: 'check if a path is ignored',
    expectedCommand: 'git check-ignore',
    expectedExample: 'git check-ignore -v app.js',
    acceptableExamples: ['git check-ignore -v app.js', 'git check-ignore app.js'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['files'],
  },
  {
    id: 'sparse-01',
    query: 'enable sparse checkout cone mode',
    expectedCommand: 'git sparse-checkout',
    expectedExample: 'git sparse-checkout init --cone',
    acceptableExamples: ['git sparse-checkout init --cone'],
    preferSimplest: true,
    expectedSkillBand: [4, 4],
    tags: ['sparse'],
  },
  {
    id: 'bundle-01',
    query: 'create a bundle of the whole repo',
    expectedCommand: 'git bundle',
    expectedExample: 'git bundle create repo.bundle --all',
    acceptableExamples: ['git bundle create repo.bundle --all'],
    preferSimplest: true,
    expectedSkillBand: [4, 4],
    tags: ['bundle'],
  },
  {
    id: 'archive-01',
    query: 'export a zip archive of HEAD',
    expectedCommand: 'git archive',
    expectedExample: 'git archive --format=zip HEAD -o repo.zip',
    acceptableExamples: ['git archive --format=zip HEAD -o repo.zip'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['archive'],
  },
  {
    id: 'gc-01',
    query: 'run garbage collection to clean the repo',
    expectedCommand: 'git gc',
    expectedExample: 'git gc',
    acceptableExamples: ['git gc', 'git gc --prune=now'],
    preferSimplest: true,
    expectedSkillBand: [3, 4],
    tags: ['maintenance'],
  },
  {
    id: 'fsck-01',
    query: 'verify connectivity and validity of objects',
    expectedCommand: 'git fsck',
    expectedExample: 'git fsck',
    acceptableExamples: ['git fsck'],
    preferSimplest: true,
    expectedSkillBand: [4, 4],
    tags: ['maintenance'],
  },
  {
    id: 'mv-01',
    query: 'rename a tracked file with git',
    expectedCommand: 'git mv',
    expectedExample: 'git mv app.js src/index.ts',
    acceptableExamples: ['git mv app.js src/index.ts'],
    preferSimplest: true,
    expectedSkillBand: [2, 3],
    tags: ['files'],
  },
];

const byId = new Map(migrated.map((c) => [c.id, c]));
for (const e of extras) {
  byId.set(e.id, migrateGoldenCase(e, DEFAULT_GLOSSARY));
}
const all = [...byId.values()];
writeFileSync('eval/golden/cases.json', `${JSON.stringify(all, null, 2)}\n`);
console.log('wrote', all.length, 'cases');
