/** Auto-generated by apps/web/scripts/export-web-pack.ts — do not edit by hand. */
export const WEB_PACK_BYTES = 8962048;
export const WEB_PACK_SHA256 = '97d505460ac9205b1701461e80c4144c3ae7d211031b7a6cef678d9cf02c049c';
export const WEB_CATALOG_URL = '/catalog/web-catalog.db';
export const MODEL_BYTES_ESTIMATE = 94371840;
export const MODEL_DOWNLOAD_MB = 90;
export const MODEL_DOWNLOAD_LABEL = '~90 MB';
export const PLAYGROUND_DOWNLOAD_MB = 99;
export const PLAYGROUND_DOWNLOAD_LABEL = '~99 MB (catalog ~9 MB + model ~90 MB)';
