/** Auto-generated by scripts/export-web-pack.ts — do not edit by hand. */
export const WEB_PACK_BYTES = 25202688;
export const WEB_PACK_SHA256 = '45b7a816460e54fee4867c4477a00d7c0cdad20feb04e8e27e9c0ffab46c640e';
export const WEB_CATALOG_URL = '/catalog/web-catalog.db';
export const MODEL_BYTES_ESTIMATE = 94371840;
export const MODEL_DOWNLOAD_MB = 90;
export const MODEL_DOWNLOAD_LABEL = '~90 MB';
export const PLAYGROUND_DOWNLOAD_MB = 115;
export const PLAYGROUND_DOWNLOAD_LABEL = '~115 MB (catalog ~25 MB + model ~90 MB)';
