/** Auto-generated by scripts/export-web-pack.js — do not edit by hand. */
export const WEB_PACK_BYTES = 14136269;
export const WEB_PACK_SHA256 = 'c3720274889f51a153c64097420b784ba2e31c3db0518f6d5dcd0257120a63a0';
export const MODEL_BYTES_ESTIMATE = 94371840;
export const MODEL_DOWNLOAD_MB = 90;
export const MODEL_DOWNLOAD_LABEL = '~90 MB';
export const PLAYGROUND_DOWNLOAD_MB = 104;
export const PLAYGROUND_DOWNLOAD_LABEL = '~104 MB';
